### ISSUE TITLE
[Feature]: Use Recommended Labels in K8s generator

### ISSUE THREAD

**Issue by svrnm** [cisco-open/app-simulator#122]
### Problem Statement

The generated k8s manfiests use labels like `service` and `app`, they seem to be commonly used, but not official. Also the current setup creates a view in cilium hubble like this:

![Screenshot 2025-01-13 at 10 06 14](https://github.com/user-attachments/assets/da076746-e2e5-418a-9f9d-4e9a9a28d478)

### Proposed Solution

K8s has a set of "recommended labels" which are also supported by a variety of tools (e.g. cilium), we should use them instead of `app` or `service`.

The recommended labels are listed here: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

So we could do something like the following defaults

```
metadata:
  labels:
    app.kubernetes.io/name: <name of the service, database, loader>
    app.kubernetes.io/instance: <name of the service, database, loader>-<randomly generated id>
    app.kubernetes.io/version: <version of the used image>
    app.kubernetes.io/component: <service or database or loader>
    app.kubernetes.io/part-of: <default to ApplicationSimulator>
```

Additionally we allow them to be overwritten by the user. 

### Checklist

- [X] I have read the [contributing guidelines](/cisco-open/app-simulator/blob/main/CONTRIBUTING.md)
- [X] I have verified this does not duplicate an existing feature request
